const colors = {
  transparent: 'transparent',
  current: 'currentColor',

  white: 'var(--color-white)',
  black: 'var(--color-black)',
  dark: {
    1: 'var(--color-basic-1)',
    2: 'var(--color-basic-2)',
    3: 'var(--color-basic-3)',
    4: 'var(--color-basic-4)',
    5: 'var(--color-basic-5)',
    6: 'var(--color-basic-6)',
    7: 'var(--color-basic-7)',
    8: 'var(--color-basic-8)',
    9: 'var(--color-basic-9)',
    10: 'var(--color-basic-10)',
    11: 'var(--color-basic-11)',
    12: 'var(--color-basic-12)',
    13: 'var(--color-basic-13)',
  },
  primary: {
    1: 'var(--color-primary-1)',
    2: 'var(--color-primary-2)',
    3: 'var(--color-primary-3)',
    4: 'var(--color-primary-4)',
    5: 'var(--color-primary-5)',
    6: 'var(--color-primary-6)',
    7: 'var(--color-primary-7)',
    8: 'var(--color-primary-8)',
    9: 'var(--color-primary-9)',
    10: 'var(--color-primary-10)',
  },
  success: {
    1: 'var(--color-success-1)',
    2: 'var(--color-success-2)',
    3: 'var(--color-success-3)',
    4: 'var(--color-success-4)',
    5: 'var(--color-success-5)',
    6: 'var(--color-success-6)',
    7: 'var(--color-success-7)',
    8: 'var(--color-success-8)',
    9: 'var(--color-success-9)',
  },
  warning: {
    1: 'var(--color-warning-1)',
    2: 'var(--color-warning-2)',
    3: 'var(--color-warning-3)',
    4: 'var(--color-warning-4)',
    5: 'var(--color-warning-5)',
    6: 'var(--color-warning-6)',
    7: 'var(--color-warning-7)',
    8: 'var(--color-warning-8)',
    9: 'var(--color-warning-9)',
    10: 'var(--color-warning-10)',
  },
  danger: {
    1: 'var(--color-danger-1)',
    2: 'var(--color-danger-2)',
    3: 'var(--color-danger-3)',
    4: 'var(--color-danger-4)',
    5: 'var(--color-danger-5)',
    6: 'var(--color-danger-6)',
    7: 'var(--color-danger-7)',
    8: 'var(--color-danger-8)',
    9: 'var(--color-danger-9)',
  },
};

module.exports = {
  colors,
};
